### ISSUE TITLE
version-check update

### ISSUE THREAD

**Issue by cholcombe973** [SergioBenitez/proc-macro2-diagnostics#2]
Hi Sergio 👋 
Could you cut a new release of this crate with the latest version of `version-check`? I'm running into a version conflict with a few other libraries and it looks like the root of it is this library being pinned on `0.9.1`. 
If you'd like me to put up a PR I'm happy to do that.

**Comment by SergioBenitez** [comment]
The version isn't pinned, however. This crate declares:

```
version_check = "0.9.1"
```

Which is equivalent to `^0.9.1` which means any `0.9` release >= `0.9.1`.

**Comment by cholcombe973** [comment]
Ah ok that makes sense. Would it be possible to bump it up to `0.9.4` or would that break things?

**Comment by SergioBenitez** [comment]
It would be possible, and it likely wouldn't break things unless some other crate _did_ pin the version or use a maximum version bound, but it shouldn't fix anything either. I don't think the issue you're seeing has anything to do with how this dependency is set here.

**Comment by cholcombe973** [comment]
Ok I'll keep digging to see if I can find the real root :). I suspect it's actix-web and cookie which has a `^0.9.4` line for `version_check`

**Comment by SergioBenitez** [comment]
Can you post the error you're getting? Perhaps I can help you debug it.

**Comment by cholcombe973** [comment]
Yeah when I combine `actix-web` with `anchor-client` from solana I get this:
```
chrisholcombe@Chriss-MacBook-Pro nft_service % cargo check
    Updating crates.io index
error: failed to select a version for `version_check`.
    ... required by package `cookie v0.16.1`
    ... which satisfies dependency `cookie = "^0.16"` of package `actix-web v4.0.0`
    ... which satisfies dependency `actix-web = "^4"` of package `nft_service v0.1.0 (/Users/chrisholcombe/repos/nft_service)`
versions that meet the requirements `^0.9.4` are: 0.9.4

all possible versions conflict with previously selected packages.

  previously selected package `version_check v0.9.2`
    ... which satisfies dependency `version_check = "^0.9.1"` of package `proc-macro2-diagnostics v0.9.1`
    ... which satisfies dependency `proc-macro2-diagnostics = "^0.9"` of package `anchor-syn v0.24.2`
    ... which satisfies dependency `anchor-syn = "^0.24.2"` of package `anchor-attribute-access-control v0.24.2`
    ... which satisfies dependency `anchor-attribute-access-control = "^0.24.2"` of package `anchor-lang v0.24.2`
    ... which satisfies dependency `anchor-lang = "^0.24.2"` of package `anchor-client v0.24.2`
    ... which satisfies dependency `anchor-client = "^0.24.2"` of package `nft_service v0.1.0 (/Users/chrisholcombe/repos/nft_service)`
```

**Comment by jplatte** [comment]
Try `cargo update` and / or `cargo clean`.

**Comment by SergioBenitez** [comment]
Since this isn't an issue here and isn't actionable, I'm closing this out.
