### ISSUE TITLE
Should explicitly specify features needed from `syn`

### ISSUE THREAD

**Issue by Techcable** [SergioBenitez/proc-macro2-diagnostics#4]
Right now, the crate specifies [`syn = "2"`](https://github.com/SergioBenitez/proc-macro2-diagnostics/blob/45fa2d68669d10daeaf0f9b664a96576626fae16/Cargo.toml#L20), which pulls in all the default features from `syn`.

Instead, the crate should specify the features it needs explicitly.

**Comment by SergioBenitez** [comment]
Sure. Send a PR!
